default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  timeout: 5000
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: kubiko_development
test:
  <<: *default
  database: kubiko_development
